services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
    container_name: redis
    ports:
      - "6377:6379"
    cpuset: "0-3"
    ulimits:
      memlock: -1
    restart: unless-stopped

  keydb:
    build:
      context: .
      dockerfile: Dockerfile-keydb
    container_name: keydb
    ports:
      - "6380:6379"
    cpuset: "0-3"
    ulimits:
      memlock: -1
    restart: unless-stopped

  dragonfly:
    build:
      context: .
      dockerfile: Dockerfile-dragonfly
    container_name: dragonfly
    ports:
      - "6381:6379"
    cpuset: "0-3"
    ulimits:
      memlock: -1
    restart: unless-stopped

  valkey:
    build:
      context: .
      dockerfile: Dockerfile-valkey
    container_name: valkey
    ports:
      - "6382:6379"
    cpuset: "0-3"
    ulimits:
      memlock: -1
    restart: unless-stopped

  redis-tls:
    build:
      context: .
      dockerfile: Dockerfile-redis-tls
    container_name: redis-tls
    ports:
      - "6390:6390"
    cpuset: "0-3"
    ulimits:
      memlock: -1
    restart: unless-stopped

  keydb-tls:
    build:
      context: .
      dockerfile: Dockerfile-keydb-tls
    container_name: keydb-tls
    ports:
      - "6391:6391"
    cpuset: "0-3"
    ulimits:
      memlock: -1
    restart: unless-stopped

  dragonfly-tls:
    build:
      context: .
      dockerfile: Dockerfile-dragonfly-tls-nopass
    container_name: dragonfly-tls
    ports:
      - "6392:6392"
    cpuset: "0-3"
    ulimits:
      memlock: -1
    restart: unless-stopped

  valkey-tls:
    build:
      context: .
      dockerfile: Dockerfile-valkey-tls
    container_name: valkey-tls
    ports:
      - "6393:6393"
    cpuset: "0-3"
    ulimits:
      memlock: -1
    restart: unless-stopped